const engine=process.env.OUTRAGE_BROWSER||'chromium',browserType=require(process.env.OUTRAGE_PLAYWRIGHT)[engine],fs=require('fs'),assert=require('node:assert/strict');
(async()=>{const b=await browserType.launch({headless:true,...(engine==='chromium'?{executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'}:{})});try{
const p=await b.newPage({viewport:{width:1440,height:900}}),errors=[];p.on('pageerror',e=>errors.push(e.stack));
await p.goto('http://127.0.0.1:8765/index.html?debug=1');await p.waitForFunction(()=>window.OUTankTest&&window.OUTank3D?.sentryReady,null,{timeout:90000});await p.locator('#fogOff').check();await p.locator('#startBtn').click();await p.waitForFunction(()=>OUTankTest.running);
await p.evaluate(()=>{const g=OUTankTest;g.ai.tick=()=>{};for(const u of g.units)u.alive=false;for(let y=10;y<31;y++)for(let x=10;x<31;x++){const i=y*g.MAP_W+x;g.terrain[i]=0;g.treeHp[i]=0;g.ore[i]=0;}window.gun=g.addBuilding(0,'turret',20,20);gun.hp=gun.hpMax=1000000;gun._placedAt=g.state.t+10000;window.pack=[];for(let i=0;i<60;i++){const a=(i%20)*Math.PI/10,r=220+Math.floor(i/20)*110,u=g.addUnit(1,'tank',gun.x+Math.cos(a)*r,gun.y+Math.sin(a)*r,{skipMvp:true});u.hp=u.hpMax=100000;u.order={type:'guard',x:u.x,y:u.y};pack.push(u);}g.centerCameraOn(gun.x,gun.y);window.samples=[];const fn=g.sim.tickSim;g.sim.tickSim=function(dt){const t=performance.now();const result=fn(dt);samples.push(performance.now()-t);return result;};});
await p.waitForTimeout(2500);const baseline=await p.evaluate(()=>{const a=samples.splice(0).sort((a,b)=>a-b);return{n:a.length,p95:a[Math.floor(a.length*.95)],max:a.at(-1)}});
await p.evaluate(()=>{const g=OUTankTest;window.orders=new Map(pack.map(u=>[u.id,u.order]));window.orderChanges=0;window.reacted=new Set();window.lastDamage=-1e9;window.massStart=g.state.t;const fn=g.sim.tickSim;g.sim.tickSim=function(dt){if(g.state.t-lastDamage>.6){lastDamage=g.state.t;for(const u of pack)g.applyDamage(u,1,gun.id,0);}const r=fn(dt);for(const u of pack){if(u.target===gun.id)reacted.add(u.id);if(orders.get(u.id)!==u.order){orderChanges++;orders.set(u.id,u.order);}}return r;};});
await p.waitForFunction(()=>OUTankTest.state.t-massStart>=5,null,{timeout:25000});
const combat=await p.evaluate(()=>{const a=samples.sort((a,b)=>a-b);return{n:a.length,p95:a[Math.floor(a.length*.95)],max:a.at(-1),reacted:reacted.size,orderChanges,pathStats:{...OUTankTest.sim.pathStats}}});assert.equal(combat.reacted,60);assert(combat.orderChanges<=120,'Repeated damage resets attack orders');assert.equal(errors.length,0);const result={baseline,combat,errors};fs.writeFileSync(process.argv[2],JSON.stringify(result,null,2));console.log(result);
}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1});
